import "../common.just"

default: (_build-ruby "ruby") (_build-ruby-distroless "ruby-distroless")

[private]
_build-ruby-distroless image_name:
    #!/usr/bin/env bash
    set -euo pipefail
    ruby_version=$(awk -F= '/^ARG RUBY_VERSION=/ {print $2}' Dockerfile)
    distroless_debian_version=$(docker run --rm ruby:${ruby_version} sh -c '. /etc/os-release && echo $VERSION_ID')
    docker build --pull --target distroless --build-arg RUBY_VERSION=${ruby_version} --build-arg DISTROLESS_DEBIAN_VERSION=${distroless_debian_version} -t {{image_name}} .
