name: Build nvim

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'nvim/**'
      - '!**/*.md'
      - '!**/justfile'
  push:
    branches:
      - main
      - 'renovate/**'
    paths:
      - 'nvim/**'
      - '!**/*.md'
      - '!**/justfile'

permissions: {}

jobs:
  build:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reusable-debian-image.yml
    with:
      image_name: nvim
      debian_tag: trixie-debian13
      release_tag: '13'
      default_git_user_name: zewelor
      default_git_user_email: zewelor@gmail.com
      publish: ${{ github.ref == 'refs/heads/main' }}
      test_command: 'docker run --rm test-image:latest --version'
    secrets: inherit
