name: Build all images

on:
  workflow_dispatch:
    inputs:
      use_cache:
        description: 'Use Docker cache'
        type: boolean
        default: true
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/**'
  push:
    branches:
      - main
      - 'renovate/**'
    paths:
      - '.github/workflows/**'
  schedule:
    - cron: '0 0 * * 0'

env:
  DOCKER_BUILD_CHECKS_ANNOTATIONS: false

jobs:
  latest-alpine:
    name: Discover previous stable Alpine
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.fetch_version.outputs.previous_stable_alpine }}
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - id: fetch_version
        name: Fetch Previous Stable Alpine Version
        run: |
          alpine_version="$(./scripts/get_previous_stable_alpine.sh)"
          echo "$alpine_version" | grep -Eq '^[0-9]+\.[0-9]+$'
          echo "Previous stable Alpine version: $alpine_version"
          echo "previous_stable_alpine=$alpine_version" >> "$GITHUB_OUTPUT"

  alpine:
    name: Build ${{ matrix.image_name }}
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    needs: latest-alpine
    strategy:
      fail-fast: false
      matrix:
        image_name: [rsync, tftp, sqlite3]
    uses: ./.github/workflows/reusable-alpine-image.yml
    with:
      image_name: ${{ matrix.image_name }}
      alpine_version: ${{ needs.latest-alpine.outputs.version }}
      publish: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main' }}
      use_cache: ${{ github.event_name != 'workflow_dispatch' || inputs.use_cache }}
    secrets: inherit

  ruby:
    name: Build ruby
    uses: ./.github/workflows/reusable-ruby-image.yml
    with:
      publish: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main' }}
      use_cache: ${{ github.event_name != 'workflow_dispatch' || inputs.use_cache }}
    secrets: inherit
