name: Build sqlite3

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'sqlite3/**'
      - '!**/*.md'
      - '!**/Justfile'
  push:
    branches:
      - main
      - 'renovate/**'
    paths:
      - 'sqlite3/**'
      - '!**/*.md'
      - '!**/Justfile'

jobs:
  build:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    uses: ./.github/workflows/reusable-alpine-image.yml
    with:
      image_name: sqlite3
      publish: ${{ github.ref == 'refs/heads/main' }}
    secrets: inherit
