name: Build tftp image

on:
  workflow_dispatch:
    inputs:
      use_cache:
        description: Use Docker cache
        type: boolean
        default: true
  pull_request:
    types: [opened, synchronize, reopened]
    paths: &image_paths
      - 'tftp/**'
      - '!tftp/**/*.md'
      - '!tftp/justfile'
  push:
    branches:
      - main
      - 'renovate/**'
    paths: *image_paths

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    name: Build and publish
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
    uses: ./.github/workflows/reusable-alpine-image.yml
    with:
      image_name: tftp
      publish: ${{ github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main' }}
      use_cache: ${{ github.event_name != 'workflow_dispatch' || inputs.use_cache }}
    secrets: inherit
