name: Reusable alpine image build

on:
  workflow_call:
    inputs:
      image_name:
        description: Image directory name
        required: true
        type: string
      alpine_version:
        description: Resolved Alpine version to build against
        required: true
        type: string
      publish:
        description: Push image to registry
        required: false
        default: false
        type: boolean
      use_cache:
        description: Use Docker cache
        required: false
        default: true
        type: boolean

env:
  DOCKER_BUILD_CHECKS_ANNOTATIONS: false

jobs:
  build:
    name: Build ${{ inputs.image_name }}
    runs-on: ubuntu-latest
    env:
      TEST_TAG: ${{ github.repository_owner }}/${{ inputs.image_name }}:test
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: ${{ inputs.image_name }}/Dockerfile
          ignore: DL3018
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}
          tags: |
            # full length sha
            type=sha,format=long,prefix=
            type=raw,enable=true,priority=200,prefix=,suffix=,value=alpine-${{ inputs.alpine_version }}
          flavor: |
            latest=true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Login to dhi.io
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 30
          max_attempts: 3
          command: |
            echo "${{ secrets.DOCKER_DHI_TOKEN }}" | docker login dhi.io -u "${{ secrets.DOCKER_DHI_USERNAME }}" --password-stdin
      - name: Login to GitHub Container Registry
        if: ${{ inputs.publish }}
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v7
        with:
          pull: true
          push: ${{ inputs.publish }}
          context: ${{ inputs.image_name }}/
          build-args: |
            ALPINE_VERSION=${{ inputs.alpine_version }}
          cache-from: ${{ inputs.use_cache && format('type=gha,scope={0}', inputs.image_name) || '' }}
          cache-to: type=gha,mode=max,scope=${{ inputs.image_name }}
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
